services:
   faianca.blog.admin.post:
      class: Faianca\BlogBundle\Admin\PostAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: faianca_blog, label: post }
      arguments: [null, Faianca\BlogBundle\Entity\Post, FaiancaBlogBundle:PostAdmin]
